# Generated by Django 5.2.6 on 2025-09-08 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blogs", "0003_rename_category_blog_category_alter_blog_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="blog",
            old_name="creared_at",
            new_name="created_at",
        ),
    ]
